name: release
on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release"
        required: true

env:
  RELEASE: ${{ github.event.inputs.release }}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.0"

      - name: Release
        run: |
          sudo chmod 755 ./release.sh
          ./release.sh ${{ env.RELEASE }}
